version: '3'

services:
  consulserver01:
    image: consul:1.10
    container_name: consulserver01
    hostname: consulserver01
    command: ['tail', '-f', '/dev/null']

  consulserver02:
    image: consul:1.10
    container_name: consulserver02
    hostname: consulserver02
    command: ['tail', '-f', '/dev/null']

  consulserver03:
    image: consul:1.10
    container_name: consulserver03
    hostname: consulserver03
    command: ['tail', '-f', '/dev/null']

  consulclient01:
    image: consul:1.10
    container_name: consulclient01
    hostname: consulclient01
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul01:/etc/consul.d
